config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users do
    member do
      get :following, :followers
    end
    resources :favorites
  end

  resources :relationships, only: %i[create destroy]

  resources :articles do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  get 'tags/:tag', to: 'articles#index', as: :tag

  post '/home/guest_sign_in', to: 'home#new_guest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :channnel_name, presence: true
  validates :thumbnail, presence: true, uniqueness: true

  enum status: {
    public: 0, # 公開
    private: 1 # 非公開
  }, _prefix: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"

  belongs_to :following, class_name: "User"

  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def already_favorited?(article)
    favorites.exists?(article_id: article.id)
  end

  has_many :comments, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :name, presence: true
  validates :login_id, presence: true, uniqueness: true

  # フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  mount_uploader :icon, IconUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[login_id name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles
  def index
    @articles = Article.where(status: :public).order(created_at: :desc)

    @articles = Article.tagged_with(params[:tag].to_s) if params[:tag]
  end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments.order(created_at: :desc)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    @article = Article.new(article_params)
    url = params[:article][:thumbnail]
    url = url.last(11)
    @article.thumbnail = url

    @article.user_id = current_user.id

    if @article.save
      redirect_to @article, notice: '記事を投稿しました。'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: '投稿内容を更新しました。'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: '投稿を削除しました。'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def article_params
    params.require(:article).permit(:title, :channnel_name, :content, :thumbnail, :status, :start_time, :user_id, :comment, :tag_list)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :article_id, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    @articles = Article.joins(:favorites).where(favorites: { user_id: params[:user_id] }, status: :public)
  end

  def create
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.build(article_id: params[:article_id])
    favorite.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.find_by(article_id: @article.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path if user_signed_in?
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.login_id = 'guestuser'
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    @user = User.find(params[:following_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @articles = if current_user == @user
                  @user.articles.order(created_at: :desc)
                else
                  @user.articles.where(status: :public).order(created_at: :desc)
                end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: '不正なアクセスです。'
    else
      render :edit
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:login_id, :name, :icon, :profile, :remove_icon, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs4_bgcolor_for(flash_key)
    case flash_key
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_key.to_s
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="card" style="width: 50rem; padding: 20px; margin:0 auto;">
<%= form_with(model: article, local: true) do |form| %>

　<%#エラーメッセージ%>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <i class="fas fa-caret-square-right"></i>
    <%= form.label :動画タイトル %>
    <span class="badge badge-danger">必須</span>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <i class="fas fa-tv"></i>
    <%= form.label :チャンネル名 %>
    <span class="badge badge-danger">必須</span>
    <%= form.text_field :channnel_name %>
  </div>
  
  <div class="field">
    <i class="fas fa-link"></i>
    <%= form.label :動画リンク（動画概要欄の共有からリンクを貼ってください） %>
    <span class="badge badge-danger">必須</span>
    <%= form.text_field :thumbnail %>
  </div>
  
  <div class="field">
    <i class="far fa-comment"></i>
    <%= form.label :ひとこと %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <i class="fas fa-tags"></i>
    <%= form.label :タグ（複数タグを付ける場合は半角カンマで区切ってください） %>
    <%= form.text_field :tag_list, value:@article.tag_list.join(','), class: "form-control" %>
  </div>

  <div class="field">
    <i class="fas fa-lock-open"></i>
    <%= form.label :公開状況 %>
    <%= form.select :status,  Article.statuses.keys.map {|k| [I18n.t("enums.article.status.#{k}"), k]}  %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/articles/_tag_list.html.erb
<% Article.tag_list.each do |tag| %>
  <span class="badge badge-primary.mr-1.p-2"><%= tag %></span>
<% end %>

app/views/articles/edit.html.erb
<h4 style="width: 50rem; margin:20px auto; text-align:center; font-family: 'Microsoft Sans Serif',sans-serif; font-weight:bold;"><i class="fas fa-edit"></i>記事の編集</h4>

<div class="card" style="width: 50rem; padding: 20px; margin:0 auto;">
<%= form_with(model: @article, local: true) do |form| %>

　<%#エラーメッセージ%>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <i class="fas fa-caret-square-right"></i>
    <%= form.label :動画タイトル %>
    <span class="badge badge-danger">必須</span>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <i class="fas fa-tv"></i>
    <%= form.label :チャンネル名 %>
    <span class="badge badge-danger">必須</span>
    <%= form.text_field :channnel_name %>
  </div>
  
  <div class="field">
    <i class="far fa-comment"></i>
    <%= form.label :ひとこと %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <i class="fas fa-tags"></i>
    <%= form.label :タグ（複数タグを付ける場合は半角カンマで区切るようにしてください） %>
    <%= form.text_field :tag_list, value:@article.tag_list.join(','), class: "form-control" %>
  </div>

  <div class="field">
    <i class="fas fa-lock-open"></i>
    <%= form.label :公開状況 %>
    <%= form.select :status,  Article.statuses.keys.map {|k| [I18n.t("enums.article.status.#{k}"), k]}  %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
    <%= link_to '記事を削除', article_path(@article), method: :delete, data: { confirm: '本当に削除してよろしいですか?'}  , class: 'btn btn-danger' %>
  </div>
  
<% end %>
</div>

<div style="width: 50rem; margin:20px auto;">
 <%= link_to '記事に戻る', @article %><br>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<div class="card" style="width: 50rem; margin:20px auto;">
  <div class="card-body">
    
    <%# ユーザーアイコン　%>
    <div class="media">
      <% if article.user.icon? %>
        <%= image_tag article.user.icon.url, width: '50px' , class: 'icon_image'  %>
      <% else %>
        <image src="/assets/default.png" width= "50px" class = "icon_image">
      <% end %>
    
    <div class="media-body" style="margin-left:12px;">
      <p class="m-0" style="font-weight:bold;"><%= link_to user_path(article.user)do %><%= article.user.name %><% end %></p>
      <p class="m-0" style="color: #808080;"><i class="fas fa-clock"></i><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    </div>
    </div>
  </div>
    
  <%# 動画　%>
  <iframe class="card-img-top" style="width: 50rem; height: 28rem; margin:0 auto; " src="https://www.youtube.com/embed/<%= article.thumbnail%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  
  <div class="card-body">
    <%# いいね　%>
    <h3 class="favorites_buttons_<%= article.id %>">
      <%= render partial: 'favorites/favorite', locals: {article: article} %>
  　</h3>
    
    <%# タイトル　%>
    <h5 class="card-title" style="font-weight:bold;">
      <i class="fas fa-caret-square-right"></i>
      <%= article.title %>
    </h5>
    
    <%# チャンネル名　%>
    <p class="card-channnel">
    <i class="fas fa-tv"></i>
    <%= article.channnel_name %></p>
    
    <%# ひとこと・タグ　%>
    <li class="list-group-item">
      <p class="m-0" style="font-weight:bold;"><i class="far fa-comment"></i><%= link_to user_path(article.user)do %><%= article.user.name %><% end %></p>
      <%= article.content %>
      <p>
        <% article.tag_list.each do |tag| %>
          <span class="badge badge-primary"><%= tag %></span>
        <% end %>
      </p>
    </li>
  </div>
  
</div>
<% end %>

app/views/articles/new.html.erb
<h4 style="width: 50rem; margin:20px auto; text-align:center; font-family: 'Microsoft Sans Serif',sans-serif; font-weight:bold;"><i class="fas fa-edit"></i>新規投稿</h4>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="card" style="width: 50rem; margin:20px auto;">
  <div class="card-body">
    
    <%# ユーザーアイコン　%>
    <div class="media">
    <% if @article.user.icon? %>
      <%= image_tag @article.user.icon.url, width: '50px' , class: 'icon_image' %>
    <% else %>
      <image src="/assets/default.png" width= "50px" class = "icon_image">
    <% end %>
    
    <%# ユーザー名　%>
    <div class="media-body" style="margin-left:12px;">
      <p class="m-0" style="font-weight:bold;"><%= link_to user_path(@article.user)do %><%= @article.user.name %><% end %></p>
      <p class="m-0" style="color: #808080;"><i class="fas fa-clock"></i><%= @article.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    </div>
    
    <%# ログインユーザーの場合　%>
    <% if @article.user.id == current_user.id %>
    <div style="text-align : right;">
      <i class="fas fa-edit"></i><%= link_to '編集', edit_article_path(@article) %>
      <i class="far fa-eye"></i><%= @article.status_i18n %>
    </div>
    <% end %>
    </div>
  </div>
    
  <%# 動画　%>
  <iframe class="card-img-top" style="width: 50rem; height: 28rem; margin:0 auto; " src="https://www.youtube.com/embed/<%= @article.thumbnail%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  
  <div class="card-body">
    <%# いいね　%>
    <h3 class="favorites_buttons_<%= @article.id %>">
      <%= render partial: 'favorites/favorite', locals: {article: @article} %>
  　</h3>
    
    <%# タイトル　%>
    <h5 class="card-title" style="font-weight:bold;">
      <i class="fas fa-caret-square-right"></i>
      <%= @article.title %>
    </h5>
    
    <%# チャンネル名　%>
    <p class="card-channnel">
    <i class="fas fa-tv"></i>
    <%= @article.channnel_name %></p>
    
    <%# ひとこと・タグ　%>
    <li class="list-group-item">
      <p class="m-0" style="font-weight:bold;"><i class="far fa-comment"></i><%= link_to user_path(@article.user)do %><%= @article.user.name %><% end %></p>
      <%= @article.content %>
      <p>
        <% @article.tag_list.each do |tag| %>
          <span class="badge badge-primary"><%= tag %></span>
        <% end %>
      </p>
    </li>
  </div>
  
</div>

app/views/comments/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with(model: [article, comment], url: article_comments_path(@article) ) do |f| %>
  <%= f.text_area :content, class: "input-mysize" %>
  <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            
            <div class="comment-text">
                <p><%= link_to "@#{comment.user.name}", user_path(comment.user.id) %></p>
                <div class="comment-entry">
                    <%= comment.content %>
                    <% if comment.user == current_user %>
                        <%= link_to article_comment_path(comment.article_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                </div>
                <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </span>
            </div>
        </div>
    </li>
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        
                        <div class="comment-text">
                            <p><%= link_to "@#{comment.user.name}", user_path(comment.user.id) %></p>
                            <div class="comment-entry">
                                <%= comment.content %>
                                <% if comment.user == current_user %>
                                    <%= link_to article_comment_path(comment.article_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.article.comments }) %>")
$("textarea").val('')

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
    <% if current_user.already_favorited?(article) %>
        <%=link_to article_favorites_path(article.id), method: :delete, remote: true, class: "fas fa-heart", style: "color: red;" do%><% end %>
        <%= article.favorites.count %>
    <% else %>
        <%=link_to article_favorites_path(article.id), method: :post, remote: true, class: "far fa-heart" , style: "color: red;" do%><% end %>
        <%= article.favorites.count %>
    <% end %>

<% end %>

app/views/favorites/create.js.erb
$('.favorites_buttons_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {article: @article}) %>");

app/views/favorites/destroy.js.erb
$('.favorites_buttons_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {article: @article}) %>");

app/views/favorites/index.html.erb
<h4 style="width: 50rem; margin:20px auto; text-align:center; font-family: 'Microsoft Sans Serif',sans-serif; font-weight:bold; "><i class="fas fa-heart" style="color:red;"></i>いいね一覧</h4>
<div class="row" style="width: 60rem; margin:0 auto;">
<% @articles.each do |article| %>
<div class="card" style="width: 18rem; margin:15px;">
  <iframe class="card-img-top" style="width: 18rem; height: 10rem; margin:0 auto;"  src="https://www.youtube.com/embed/<%= article.thumbnail%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

  <div class="card-body">
    <h6 class="card-title" style="font-weight:bold;"><i class="fas fa-caret-square-right"></i><%= link_to article.title, article_path(article) %></h6>
    <p style="color: #808080;"><i class="fas fa-clock"></i><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
  </div>
</div>
<% end %>
</div>

app/views/home/index.html.erb
<h1 class="display-1 text-white text-right font-weight-bold" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">My Favorite YouTube</h1>
<h2 class="text-right" style="color: #ccc">お気に入りの動画をシェアしよう。</h2>
<div class="text-right" style="margin-right:70px; margin-top:20px;">
    <%= link_to "新規作成", new_user_registration_path, class: "btn btn-light" %>
    <%= link_to "ログイン", new_user_session_path, class: "btn btn-light" %>
    <%= link_to 'ゲストログイン（閲覧用）', home_guest_sign_in_path, method: :post ,class: "btn btn-light" %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <%= link_to 'My Favorite YouTube', root_path, class: "navbar-brand"%>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      
   <!--もしユーザーがログインしているならば下記を表示-->
      <%  if user_signed_in?  %>
        <li class="nav-item active">
          <%= link_to 'ホーム', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to '新規投稿', new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'マイページ', current_user, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'ユーザー一覧', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
        
  <!--ログインしていないのなら下記を表示-->
      <% else %>
        <li class="nav-item active">
          <%= link_to "新規作成", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/show.html.erb
<div class="card" style="width: 50rem; padding: 20px; margin:20px auto;">
  
　<div class="container mt-1 px-5">
  　<div class="row mt-1">
    <!--左側-->
    <div class="col-md-6 ">
        <%# アイコン %>
        <% if @user.icon? %>
           <%= image_tag @user.icon.url, width: '70%' , style: 'rounded-circle', class: 'icon_image'  %>
        <% else %>
           <image src="/assets/default.png" width= "70%" class = "icon_image">
        <% end %> 
    </div>

    <!--右側-->
    <div class="col-md-6 px-3">
      
      <%# ユーザーネーム %>
      <h2 class="name"><%= @user.name %></h2>
      
      <%# ユーザーID %>
      <p style="color: #808080;"><%='@' + @user.login_id %></p>
      
      <%# プロフィール文 %>
      <p><%= @user.profile %></p>
      
      <%# フォロワー・フォロー %>
        フォロワー<%= link_to followers_user_path(@user) do %><h5 id="followers" style="color: black;"><%= @user.followers.count %></h5><% end %>
        フォロー中<%= link_to following_user_path(@user) do %><h5 id="following" style="color: black;"><%= @user.following.count %></h5><% end %>
    
    　<%# フォローボタン %>  
       <%= render "follow_form" %>
     
      <%# ログインユーザーの場合、編集画面へ %>
      <% if @user.id == current_user.id %>
        <p style="font-weight:bold;">
         <i class="fas fa-edit"></i><%= link_to '編集', edit_user_path(@user) %>
         <i class="fas fa-heart" style="color: red;"></i><%= link_to 'いいね一覧', [@user, :favorites] %>
       　<i class="fas fa-cog" style="color: gray;"></i><%= link_to 'アカウント設定', edit_user_registration_path, method: :get %>
        </p>
　  　<% end %>
      
    </div>
    
    </div>
　</div>
</div>



<%# 投稿一覧 %>
<div class="row" style="width: 60rem; margin:0 auto;">
<% @articles.each do |article| %>
  <div class="card" style="width: 18rem; margin:15px ;">
    <iframe class="card-img-top" style="width: 18rem; height: 10rem; margin:0 auto; " src="https://www.youtube.com/embed/<%= article.thumbnail%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

  <div class="card-body">
    <h6 class="card-title" style="font-weight:bold;"><i class="fas fa-caret-square-right"></i><%= link_to article.title, article_path(article) %></h6>
    <p style="color: #808080;"><i class="fas fa-clock"></i><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    <% if @user.id == current_user.id %>
      <i class="far fa-eye"></i><%= article.status_i18n %>
    <% end %>
  </div>
  </div>
<% end %>
</div>